<script language="JavaScript">
<!-- Hide
// Copyright 2004 T-Tech Inc.

function generate(qa)

{txt="<!-- Generated By T-TechTools By T-Tech Inc. (www.t-tech.org) -->\n"

txt+="<form name=answer>\n<table  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n"

txt+="<tr>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\">"

txt+="<input  type=\"button\" name=\"submit\" value=\""+document.forms[0].bn.value+"\" style=\"FONT-WEIGHT: bold; BACKGROUND:"+document.forms[0].bc.value+"; WIDTH: 100px; COLOR:  "+document.forms[0].c.value+"\" onclick=\"document.answer.a1.value = '"+document.forms[0].a1.value+"';\">"

txt+="</td>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\"><input name=a1 style=\"border:none;color:"+document.forms[0].rc.value+"\" nomodify></td>\n</tr>"

if(document.forms[0].q2.value){txt+="<tr>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\">"

txt+="<input  type=\"button\" name=\"submit\" value=\""+document.forms[0].bn.value+"\" style=\"FONT-WEIGHT: bold; BACKGROUND:"+document.forms[0].bc.value+"; WIDTH: 100px; COLOR:  "+document.forms[0].c.value+"\" onclick=\"document.answer.a2.value = '"+document.forms[0].a2.value+"';\">"

txt+="</td>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\"><input name=a2 style=\"border:none;color:"+document.forms[0].rc.value+"\" nomodify></td>\n</tr>"}

if(document.forms[0].q3.value){txt+="<tr>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\">"

txt+="<input  type=\"button\" name=\"submit\" value=\""+document.forms[0].bn.value+"\" style=\"FONT-WEIGHT: bold; BACKGROUND:"+document.forms[0].bc.value+"; WIDTH: 100px; COLOR:  "+document.forms[0].c.value+"\" onclick=\"document.answer.a3.value = '"+document.forms[0].a3.value+"';\">"

txt+="</td>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\"><input name=a3 style=\"border:none;color:"+document.forms[0].rc.value+"\" nomodify></td>\n</tr>"}

if(document.forms[0].q4.value){txt+="<tr>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\">"

txt+="<input  type=\"button\" name=\"submit\" value=\""+document.forms[0].bn.value+"\" style=\"FONT-WEIGHT: bold; BACKGROUND:"+document.forms[0].bc.value+"; WIDTH: 100px; COLOR:  "+document.forms[0].c.value+"\" onclick=\"document.answer.a4.value = '"+document.forms[0].a4.value+"';\">"

txt+="</td>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\"><input name=a4 style=\"border:none;color:"+document.forms[0].rc.value+"\" nomodify></td>\n</tr>"}

if(document.forms[0].q5.value){txt+="<tr>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\">"

txt+="<input  type=\"button\" name=\"submit\" value=\""+document.forms[0].bn.value+"\" style=\"FONT-WEIGHT: bold; BACKGROUND:"+document.forms[0].bc.value+"; WIDTH: 100px; COLOR:  "+document.forms[0].c.value+"\" onclick=\"document.answer.a5.value = '"+document.forms[0].a5.value+"';\">"

txt+="</td>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\"><input name=a5 style=\"border:none;color:"+document.forms[0].rc.value+"\" nomodify></td>\n</tr>"}

txt+="\n</table></form>\n<!-- End of  T-TechTools Question and Answer Generator Code-->"



document.forms[0].output.value=txt

}
// --> 
</script>