<?php

include '../mainfile.php';
require XOOPS_ROOT_PATH . '/header.php';
//1=Show & 0=Do not show
$xoopsOption['show_rblock'] = 1;
$xoopsOption['show_lblock'] = 1;
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<HEAD>
<script language="JavaScript">

function generate(form)

{txt="<!-- Generated By T-TechTools By T-Tech Inc. (www.t-tech.org) -->\n"

txt+="<form name=answer>\n<table  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n"

txt+="<tr>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\">"

txt+="<input  type=\"button\" name=\"submit\" value=\""+document.forms[0].bn.value+"\" style=\"FONT-WEIGHT: bold; BACKGROUND:"+document.forms[0].bc.value+"; WIDTH: 100px; COLOR:  "+document.forms[0].c.value+"\" onclick=\"document.answer.a1.value = '"+document.forms[0].a1.value+"';\">"

txt+="</td>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\"><input name=a1 style=\"border:none;color:"+document.forms[0].rc.value+"\" nomodify></td>\n</tr>"

if(document.forms[0].q2.value){txt+="<tr>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\">"

txt+="<input  type=\"button\" name=\"submit\" value=\""+document.forms[0].bn.value+"\" style=\"FONT-WEIGHT: bold; BACKGROUND:"+document.forms[0].bc.value+"; WIDTH: 100px; COLOR:  "+document.forms[0].c.value+"\" onclick=\"document.answer.a2.value = '"+document.forms[0].a2.value+"';\">"

txt+="</td>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\"><input name=a2 style=\"border:none;color:"+document.forms[0].rc.value+"\" nomodify></td>\n</tr>"}

if(document.forms[0].q3.value){txt+="<tr>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\">"

txt+="<input  type=\"button\" name=\"submit\" value=\""+document.forms[0].bn.value+"\" style=\"FONT-WEIGHT: bold; BACKGROUND:"+document.forms[0].bc.value+"; WIDTH: 100px; COLOR:  "+document.forms[0].c.value+"\" onclick=\"document.answer.a3.value = '"+document.forms[0].a3.value+"';\">"

txt+="</td>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\"><input name=a3 style=\"border:none;color:"+document.forms[0].rc.value+"\" nomodify></td>\n</tr>"}

if(document.forms[0].q4.value){txt+="<tr>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\">"

txt+="<input  type=\"button\" name=\"submit\" value=\""+document.forms[0].bn.value+"\" style=\"FONT-WEIGHT: bold; BACKGROUND:"+document.forms[0].bc.value+"; WIDTH: 100px; COLOR:  "+document.forms[0].c.value+"\" onclick=\"document.answer.a4.value = '"+document.forms[0].a4.value+"';\">"

txt+="</td>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\"><input name=a4 style=\"border:none;color:"+document.forms[0].rc.value+"\" nomodify></td>\n</tr>"}

if(document.forms[0].q5.value){txt+="<tr>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\">"

txt+="<input  type=\"button\" name=\"submit\" value=\""+document.forms[0].bn.value+"\" style=\"FONT-WEIGHT: bold; BACKGROUND:"+document.forms[0].bc.value+"; WIDTH: 100px; COLOR:  "+document.forms[0].c.value+"\" onclick=\"document.answer.a5.value = '"+document.forms[0].a5.value+"';\">"

txt+="</td>\n<td height=\"21\" colspan=\"2\" align=\"center\" valign=\"middle\"><input name=a5 style=\"border:none;color:"+document.forms[0].rc.value+"\" nomodify></td>\n</tr>"}

txt+="\n</table></form>\n<!-- End of  T-TechTools Question and Answer Generator Code-->"



document.forms[0].output.value=txt

}

</script>
</HEAD>
<BODY>
<table width="500" border="0" align="center" cellpadding="0" cellspacing="0">

  <tr class="head"> 

    <td height="21" colspan="2" align="center" valign="middle"><strong>

      Question and Answer Generator</strong></td>

  </tr>

  <form name=form>

    <tr class="even"> 

      <td align="left" valign="middle">Question #1 

        <input name="q1" type="text" id="q1"> </td>

      <td align="center" valign="middle">Answer #1 

        <input name="a1" type="text" id="a1"></td>

    </tr>

    <tr class="odd"> 

      <td align="left" valign="middle">Question #2 

        <input name="q2" type="text" id="q2"> </td>

      <td align="center" valign="middle">Answer #2 

        <input name="a2" type="text" id="a2"></td>

    </tr>

    <tr class="even"> 

      <td align="left" valign="middle">Question #3 

        <input name="q3" type="text" id="q3"> </td>

      <td align="center" valign="middle">Answer #3 

        <input name="a3" type="text" id="a3"></td>

    </tr>

    <tr class="odd"> 

      <td align="left" valign="middle">Question #4 

        <input name="q4" type="text" id="q4"> </td>

      <td align="center" valign="middle">Answer #4 

        <input name="a4" type="text" id="a4"></td>

    </tr>

    <tr class="even"> 

      <td align="left" valign="middle">Question #5 

        <input name="q5" type="text" id="q5"> </td>

      <td align="center" valign="middle">Answer #5 

        <input name="a5" type="text" id="a5"></td>

    </tr>

    <tr class="odd"> 

      <td height="21" align="left" valign="middle">Trigger Button Background Color 

        : </td>

      <td height="21" align="center" valign="middle"><input name="bc" type="text" id="bc2"></td>

    </tr>

    <tr class="even"> 

      <td height="21" align="left" valign="middle">Trigger Button Text Color : 

      </td>

      <td height="21" align="center" valign="middle"><input name="c" type="text" id="c"></td>

    </tr>

    <tr class="odd"> 

      <td height="21" align="left" valign="middle">Answer Color :</td>

      <td height="21" align="center" valign="middle"><input name="rc" type="text" id="rc"></td>

    </tr>

	<tr class="even"> 

      <td height="21" align="left" valign="middle">Button Name:</td>

      <td height="21" align="center" valign="middle"><input name="bn" type="text" value="Get Answer!"></td>

    </tr>

    <tr class="odd"> 

      <td height="21" align="center" valign="middle"><input name="show" type="button" id="show" value="Show Code!" onclick="generate(form)"></td>

      <td height="21" align="center" valign="middle"><input name="reset" type="reset" id="reset" value="Reset fields!"></td>

    </tr>

	<tr class="even">

      <td height="21" align="left" valign="middle"> </td>

      <td height="21" align="center" valign="middle"> </td>

  </tr>

    <tr class="odd" align="center"> 

      <td height="21" colspan="2" valign="middle"><textarea name="output" cols="60" rows=4 id="output"></textarea></td>

    </tr>

	<tr class="even">

     

       <td height="21" colspan="2" align="center" valign="middle"><input type=button value="Highlight all" onclick="javascript:this.form.output.focus();this.form.output.select()"></td>

  </tr>

  </form>

</table>
<p><center>

<font face="arial, helvetica" size"-2">T-TechTools<br>

by <a href="http://t-tech.org">T-Tech Inc.</a></font>

</center><p>
</body>
</html>
<?php
require XOOPS_ROOT_PATH . '/footer.php';
?>
