<SCRIPT>

function makemymod(){
	var input = document.modumake.input.value;
	output = "echo\"";
	for (var c = 0; c < input.length; c++){
		if ((input.charAt(c) == "\n" || input.charAt(c) == "\r")){
			output += "\"";
			if (c != input.length - 1) output +="\n  . \"";
			c++;
			}
		else {
			if (input.charAt(c) == "\"") {
				output += "\\\"";
				}
			else {
				if (input.charAt(c) == "\\"){
					output += "\\\\";
					}
				else {
					output += input.charAt(c);
					if (c == input.length -1) output += "\"";	
					}
				}
			}
		
		}

info="<\?php\n" + 
"### Generated By T-TechTools By T-Tech Inc. (www.t-tech.org) ####\n" +


"include("../mainfile.php");\n" +


"include(XOOPS_ROOT_PATH."/header.php");\n" +


//1=Show & 0=Do not show

"$xoopsOption['show_rblock'] = 1;\n" +

"$xoopsOption['show_lblock'] = 1;\n" +


"?>\n" +

info2=";\n" +

"<?php\n" +


"include(XOOPS_ROOT_PATH."/footer.php");\n" +


"\n?>";

	document.modumake.output.value =info+output+info2;
}

</SCRIPT>